services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123456
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  library:
    build:
      dockerfile: Dockerfile
      context: .
    image: library-backend
    container_name: library-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config/config-compose.yaml:/github.com/rogaliiik/library/config/config-compose.yaml
    ports:
      - "8080:8080"
