basePath: /
definitions:
  domain.Book:
    properties:
      author:
        type: string
      content:
        type: string
      id:
        type: integer
      name:
        maxLength: 6
        minLength: 1
        type: string
      userId:
        type: integer
    required:
    - author
    type: object
  domain.BookUpdateInput:
    properties:
      author:
        type: string
      content:
        type: string
      name:
        type: string
    type: object
  domain.User:
    properties:
      email:
        example: user@gmail.com
        type: string
      id:
        type: integer
      password:
        maxLength: 20
        minLength: 8
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  v1.bookCreateOutput:
    properties:
      id:
        type: integer
    type: object
  v1.errorMessage:
    properties:
      message:
        type: string
    type: object
  v1.signInOutput:
    properties:
      token:
        type: string
    type: object
  v1.signUpOutput:
    properties:
      id:
        type: integer
    type: object
  v1.statusOutput:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Library app.
  title: LibraryAPI
  version: "1.0"
paths:
  /v1/auth/sign-in:
    post:
      consumes:
      - application/json
      description: user sign in
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.signInOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      summary: User SignIn
      tags:
      - user-auth
  /v1/auth/sign-up:
    post:
      consumes:
      - application/json
      description: user sign up
      parameters:
      - description: user info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/v1.signUpOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      summary: User SignUp
      tags:
      - user-auth
  /v1/book:
    get:
      consumes:
      - application/json
      description: get all books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Book'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      security:
      - UserAuth: []
      summary: Book Get all
      tags:
      - bookApi
  /v1/book/{bookId}:
    delete:
      consumes:
      - application/json
      description: delete book
      parameters:
      - description: book id
        in: path
        name: bookId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.statusOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      security:
      - UserAuth: []
      summary: Book Delete
      tags:
      - bookApi
    get:
      consumes:
      - application/json
      description: book get by id
      parameters:
      - description: book id
        in: path
        name: bookId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      security:
      - UserAuth: []
      summary: Book Get by id
      tags:
      - bookApi
    put:
      consumes:
      - application/json
      description: update book
      parameters:
      - description: book update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.BookUpdateInput'
      - description: book id
        in: path
        name: bookId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.statusOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      security:
      - UserAuth: []
      summary: Book Update
      tags:
      - bookApi
  /v1/book/create:
    post:
      consumes:
      - application/json
      description: book create
      parameters:
      - description: book info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.bookCreateOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errorMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errorMessage'
      security:
      - UserAuth: []
      summary: Book Create
      tags:
      - bookApi
securityDefinitions:
  UserAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
